import { useState, useEffect, useCallback } from "react";
import { LazyStore } from "@tauri-apps/plugin-store";
import { emit } from "@tauri-apps/api/event";
import { STORE_KEYS } from "@/lib/storeKeys";
import { DEFAULT_MODES, NONE_MODE_ID } from "@/lib/modes";
import type { IconName } from "@/components/IconPicker";

// Re-export DEFAULT_MODES for components that need it
export { DEFAULT_MODES };

// LLM Provider types
export type LlmProvider = "openai" | "google" | "anthropic";

export const LLM_PROVIDERS = {
  openai: {
    id: "openai" as const,
    name: "OpenAI",
    model: "GPT-4.1 Mini",
  },
  google: {
    id: "google" as const,
    name: "Google",
    model: "Gemini 2.0 Flash",
  },
  anthropic: {
    id: "anthropic" as const,
    name: "Anthropic",
    model: "Claude 3.5 Haiku",
  },
} as const;

export interface TranscriptionRule {
  id: string;
  title: string;
  description: string;
  enabled: boolean;
  isBuiltIn: boolean;
}

export interface TranscriptionMode {
  id: string;
  name: string;
  description: string;
  /** Custom modes store their prompt here; built-in prompts are in Rust backend */
  prompt?: string;
  icon?: IconName;
  isBuiltIn: boolean;
  /** true = user manually wrote/edited the prompt, false = prompt was auto-generated by AI */
  isPromptCustom?: boolean;
}

interface Settings {
  groqApiKey: string;
  openaiApiKey: string;
  googleApiKey: string;
  anthropicApiKey: string;
  llmProvider: LlmProvider;
  language: string;
  shortcut: string;
  cancelShortcut: string;
  microphoneDeviceId: string;
  autoPaste: boolean;
  transcriptionRules: TranscriptionRule[];
  customModes: TranscriptionMode[];
  activeMode: string;
  deletedBuiltInModes: string[];
}

const DEFAULT_RULES: TranscriptionRule[] = [
  {
    id: "fix-grammar",
    title: "Fix Grammar & Spelling",
    description: "Correct grammar, spelling, and punctuation errors",
    enabled: false,
    isBuiltIn: true,
  },
  {
    id: "remove-fillers",
    title: "Remove Filler Words",
    description: "Remove 'um', 'uh', 'like', 'you know', etc.",
    enabled: false,
    isBuiltIn: true,
  },
  {
    id: "smart-punctuation",
    title: "Smart Punctuation",
    description: "Add proper sentence structure and punctuation",
    enabled: false,
    isBuiltIn: true,
  },
  {
    id: "be-concise",
    title: "Be Concise",
    description: "Remove unnecessary words and repetition",
    enabled: false,
    isBuiltIn: true,
  },
  {
    id: "professional-tone",
    title: "Professional Tone",
    description: "Maintain a professional, polished tone",
    enabled: false,
    isBuiltIn: true,
  },
];

const DEFAULT_SETTINGS: Settings = {
  groqApiKey: "",
  openaiApiKey: "",
  googleApiKey: "",
  anthropicApiKey: "",
  llmProvider: "openai",
  language: "en",
  shortcut: "CommandOrControl+Shift+Space",
  cancelShortcut: "Escape",
  microphoneDeviceId: "",
  autoPaste: true,
  transcriptionRules: DEFAULT_RULES,
  customModes: [],
  activeMode: NONE_MODE_ID,
  deletedBuiltInModes: [],
};

const store = new LazyStore("settings.json");

export function useSettings() {
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function loadSettings() {
      try {
        const groqApiKey = await store.get<string>(STORE_KEYS.GROQ_API_KEY);
        const openaiApiKey = await store.get<string>(STORE_KEYS.OPENAI_API_KEY);
        const googleApiKey = await store.get<string>(STORE_KEYS.GOOGLE_API_KEY);
        const anthropicApiKey = await store.get<string>(STORE_KEYS.ANTHROPIC_API_KEY);
        const llmProvider = await store.get<string>(STORE_KEYS.LLM_PROVIDER);
        const language = await store.get<string>(STORE_KEYS.LANGUAGE);
        const shortcut = await store.get<string>(STORE_KEYS.SHORTCUT);
        const cancelShortcut = await store.get<string>(STORE_KEYS.CANCEL_SHORTCUT);
        const microphoneDeviceId = await store.get<string>(STORE_KEYS.MICROPHONE_DEVICE_ID);
        const autoPaste = await store.get<string>(STORE_KEYS.AUTO_PASTE);
        const transcriptionRulesJson = await store.get<string>(STORE_KEYS.TRANSCRIPTION_RULES);
        const customModesJson = await store.get<string>(STORE_KEYS.CUSTOM_MODES);
        const activeMode = await store.get<string>(STORE_KEYS.ACTIVE_MODE);
        const deletedBuiltInModesJson = await store.get<string>(STORE_KEYS.DELETED_BUILTIN_MODES);

        let transcriptionRules = DEFAULT_RULES;
        if (transcriptionRulesJson) {
          try {
            transcriptionRules = JSON.parse(transcriptionRulesJson);
          } catch {
            console.error("Failed to parse transcription rules");
          }
        }

        let customModes: TranscriptionMode[] = [];
        if (customModesJson) {
          try {
            customModes = JSON.parse(customModesJson);
          } catch {
            console.error("Failed to parse custom modes");
          }
        }

        let deletedBuiltInModes: string[] = [];
        if (deletedBuiltInModesJson) {
          try {
            deletedBuiltInModes = JSON.parse(deletedBuiltInModesJson);
          } catch {
            console.error("Failed to parse deleted built-in modes");
          }
        }

        setSettings({
          groqApiKey: groqApiKey ?? DEFAULT_SETTINGS.groqApiKey,
          openaiApiKey: openaiApiKey ?? DEFAULT_SETTINGS.openaiApiKey,
          googleApiKey: googleApiKey ?? DEFAULT_SETTINGS.googleApiKey,
          anthropicApiKey: anthropicApiKey ?? DEFAULT_SETTINGS.anthropicApiKey,
          llmProvider: (llmProvider as LlmProvider) ?? DEFAULT_SETTINGS.llmProvider,
          language: language ?? DEFAULT_SETTINGS.language,
          shortcut: shortcut ?? DEFAULT_SETTINGS.shortcut,
          cancelShortcut: cancelShortcut ?? DEFAULT_SETTINGS.cancelShortcut,
          microphoneDeviceId: microphoneDeviceId ?? DEFAULT_SETTINGS.microphoneDeviceId,
          autoPaste: autoPaste === "false" ? false : DEFAULT_SETTINGS.autoPaste,
          transcriptionRules,
          customModes,
          activeMode: activeMode ?? DEFAULT_SETTINGS.activeMode,
          deletedBuiltInModes,
        });
      } catch (err) {
        console.error("Failed to load settings:", err);
      } finally {
        setIsLoading(false);
      }
    }

    loadSettings();
  }, []);

  const updateShortcut = useCallback(async (shortcut: string) => {
    try {
      await store.set(STORE_KEYS.SHORTCUT, shortcut);
      setSettings((prev) => ({ ...prev, shortcut }));
    } catch (err) {
      console.error("Failed to save shortcut:", err);
    }
  }, []);

  const updateCancelShortcut = useCallback(async (cancelShortcut: string) => {
    try {
      await store.set(STORE_KEYS.CANCEL_SHORTCUT, cancelShortcut);
      setSettings((prev) => ({ ...prev, cancelShortcut }));
    } catch (err) {
      console.error("Failed to save cancel shortcut:", err);
    }
  }, []);

  const updateGroqApiKey = useCallback(async (groqApiKey: string) => {
    try {
      await store.set(STORE_KEYS.GROQ_API_KEY, groqApiKey);
      setSettings((prev) => ({ ...prev, groqApiKey }));
    } catch (err) {
      console.error("Failed to save Groq API key:", err);
    }
  }, []);

  const updateOpenaiApiKey = useCallback(async (openaiApiKey: string) => {
    try {
      await store.set(STORE_KEYS.OPENAI_API_KEY, openaiApiKey);
      setSettings((prev) => ({ ...prev, openaiApiKey }));
    } catch (err) {
      console.error("Failed to save OpenAI API key:", err);
    }
  }, []);

  const updateGoogleApiKey = useCallback(async (googleApiKey: string) => {
    try {
      await store.set(STORE_KEYS.GOOGLE_API_KEY, googleApiKey);
      setSettings((prev) => ({ ...prev, googleApiKey }));
    } catch (err) {
      console.error("Failed to save Google API key:", err);
    }
  }, []);

  const updateAnthropicApiKey = useCallback(async (anthropicApiKey: string) => {
    try {
      await store.set(STORE_KEYS.ANTHROPIC_API_KEY, anthropicApiKey);
      setSettings((prev) => ({ ...prev, anthropicApiKey }));
    } catch (err) {
      console.error("Failed to save Anthropic API key:", err);
    }
  }, []);

  const updateLlmProvider = useCallback(async (llmProvider: LlmProvider) => {
    try {
      await store.set(STORE_KEYS.LLM_PROVIDER, llmProvider);
      setSettings((prev) => ({ ...prev, llmProvider }));
    } catch (err) {
      console.error("Failed to save LLM provider:", err);
    }
  }, []);

  const updateLanguage = useCallback(async (language: string) => {
    try {
      await store.set(STORE_KEYS.LANGUAGE, language);
      setSettings((prev) => ({ ...prev, language }));
    } catch (err) {
      console.error("Failed to save language:", err);
    }
  }, []);

  const updateMicrophoneDeviceId = useCallback(async (microphoneDeviceId: string) => {
    try {
      await store.set(STORE_KEYS.MICROPHONE_DEVICE_ID, microphoneDeviceId);
      setSettings((prev) => ({ ...prev, microphoneDeviceId }));
    } catch (err) {
      console.error("Failed to save microphone device:", err);
    }
  }, []);

  const updateAutoPaste = useCallback(async (autoPaste: boolean) => {
    try {
      await store.set(STORE_KEYS.AUTO_PASTE, autoPaste ? "true" : "false");
      setSettings((prev) => ({ ...prev, autoPaste }));
    } catch (err) {
      console.error("Failed to save auto-paste setting:", err);
    }
  }, []);

  const updateActiveMode = useCallback(async (activeMode: string) => {
    try {
      await store.set(STORE_KEYS.ACTIVE_MODE, activeMode);
      setSettings((prev) => ({ ...prev, activeMode }));
    } catch (err) {
      console.error("Failed to save active mode:", err);
    }
  }, []);

  const updateTranscriptionRules = useCallback(async (rules: TranscriptionRule[]) => {
    try {
      await store.set(STORE_KEYS.TRANSCRIPTION_RULES, JSON.stringify(rules));
      setSettings((prev) => ({ ...prev, transcriptionRules: rules }));
    } catch (err) {
      console.error("Failed to save transcription rules:", err);
    }
  }, []);

  const toggleRule = useCallback(async (ruleId: string) => {
    const newRules = settings.transcriptionRules.map((rule) =>
      rule.id === ruleId ? { ...rule, enabled: !rule.enabled } : rule
    );
    await updateTranscriptionRules(newRules);
  }, [settings.transcriptionRules, updateTranscriptionRules]);

  const addRule = useCallback(async (title: string, description: string) => {
    const newRule: TranscriptionRule = {
      id: `custom-${Date.now()}`,
      title,
      description,
      enabled: false,
      isBuiltIn: false,
    };
    const newRules = [...settings.transcriptionRules, newRule];
    await updateTranscriptionRules(newRules);
  }, [settings.transcriptionRules, updateTranscriptionRules]);

  const updateRule = useCallback(async (ruleId: string, updates: Partial<TranscriptionRule>) => {
    const newRules = settings.transcriptionRules.map((rule) =>
      rule.id === ruleId ? { ...rule, ...updates } : rule
    );
    await updateTranscriptionRules(newRules);
  }, [settings.transcriptionRules, updateTranscriptionRules]);

  const deleteRule = useCallback(async (ruleId: string) => {
    const newRules = settings.transcriptionRules.filter((rule) => rule.id !== ruleId);
    await updateTranscriptionRules(newRules);
  }, [settings.transcriptionRules, updateTranscriptionRules]);

  // Notify FloatingWindow when modes change
  const emitModesUpdated = useCallback(() => {
    emit("modes-updated").catch((err) => {
      console.error("Failed to emit modes-updated event:", err);
    });
  }, []);

  // Mode CRUD operations
  const updateCustomModes = useCallback(async (modes: TranscriptionMode[]) => {
    try {
      await store.set(STORE_KEYS.CUSTOM_MODES, JSON.stringify(modes));
      setSettings((prev) => ({ ...prev, customModes: modes }));
      emitModesUpdated();
    } catch (err) {
      console.error("Failed to save custom modes:", err);
    }
  }, [emitModesUpdated]);

  const addMode = useCallback(async (name: string, description: string, prompt: string, icon?: IconName, isPromptCustom?: boolean) => {
    const newMode: TranscriptionMode = {
      id: `custom-mode-${Date.now()}`,
      name,
      description,
      prompt,
      icon,
      isBuiltIn: false,
      isPromptCustom: isPromptCustom ?? true,
    };
    const newModes = [...settings.customModes, newMode];
    await updateCustomModes(newModes);
  }, [settings.customModes, updateCustomModes]);

  const updateMode = useCallback(async (modeId: string, updates: Partial<TranscriptionMode>) => {
    const newModes = settings.customModes.map((mode) =>
      mode.id === modeId ? { ...mode, ...updates } : mode
    );
    await updateCustomModes(newModes);
  }, [settings.customModes, updateCustomModes]);

  const deleteMode = useCallback(async (modeId: string) => {
    const newModes = settings.customModes.filter((mode) => mode.id !== modeId);
    await updateCustomModes(newModes);
    // If the deleted mode was active, reset to "none"
    if (settings.activeMode === modeId) {
      await updateActiveMode(NONE_MODE_ID);
    }
  }, [settings.customModes, settings.activeMode, updateCustomModes, updateActiveMode]);

  // Delete built-in mode (adds to deleted list)
  const deleteBuiltInMode = useCallback(async (modeId: string) => {
    try {
      const newDeletedModes = [...settings.deletedBuiltInModes, modeId];
      await store.set(STORE_KEYS.DELETED_BUILTIN_MODES, JSON.stringify(newDeletedModes));
      setSettings((prev) => ({ ...prev, deletedBuiltInModes: newDeletedModes }));
      emitModesUpdated();
      // If the deleted mode was active, reset to "none"
      if (settings.activeMode === modeId) {
        await updateActiveMode(NONE_MODE_ID);
      }
    } catch (err) {
      console.error("Failed to delete built-in mode:", err);
    }
  }, [settings.deletedBuiltInModes, settings.activeMode, updateActiveMode, emitModesUpdated]);

  return {
    settings,
    isLoading,
    updateGroqApiKey,
    updateOpenaiApiKey,
    updateGoogleApiKey,
    updateAnthropicApiKey,
    updateLlmProvider,
    updateLanguage,
    updateShortcut,
    updateCancelShortcut,
    updateMicrophoneDeviceId,
    updateAutoPaste,
    updateActiveMode,
    updateTranscriptionRules,
    toggleRule,
    addRule,
    updateRule,
    deleteRule,
    addMode,
    updateMode,
    deleteMode,
    deleteBuiltInMode,
  };
}

